

### Mode: GFuzz | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.004s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.105s
FAIL


### Mode: GFuzzHB | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.004s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.106s
FAIL
Bugreport info: 0_1,fail


### Mode: Flow | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.005s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.108s
FAIL
Bugreport info: 0_1,fail


### Mode: GFuzzHBFlow | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.110s
FAIL
Bugreport info: 0_1,fail


### Mode: GoPie | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.005s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.106s
FAIL


### Mode: GoPie+ | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.107s
FAIL


### Mode: GoPieHB | Subdir: file(5)-test(1)-command_test-TestWrongGroupForHelp ###

=== RUN   TestWrongGroupForHelp
--- PASS: TestWrongGroupForHelp (0.00s)
PASS
ok  	github.com/spf13/cobra	0.007s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
TestName:  TestWrongGroupForHelp
Import added at line: 17
Header added at line: 2089
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/cobra-main/command_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestWrongGroupForHelp

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: group id 'wrong' is not defined for subcommand 'root help'

FAIL	github.com/spf13/cobra	0.111s
FAIL
Bugreport info: 0_1,fail
