

### Mode: GFuzz | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.110s
FAIL


### Mode: GFuzzHB | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.110s
FAIL


### Mode: Flow | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.109s
FAIL


### Mode: GFuzzHBFlow | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.005s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.109s
FAIL


### Mode: GoPie | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.007s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.109s
FAIL


### Mode: GoPie+ | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.007s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.108s
FAIL


### Mode: GoPieHB | Subdir: file(36)-test(1)-tree_test-TestTreeWildcard ###

=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.00s)
=== RUN   TestTreeWildcardConflict
--- PASS: TestTreeWildcardConflict (0.00s)
=== RUN   TestTreeWildcardConflictEx
--- PASS: TestTreeWildcardConflictEx (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeWildcard
Import added at line: 7
Header added at line: 138
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 394
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
Header added at line: 942
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeWildcard
--- PASS: TestTreeWildcard (0.10s)
=== RUN   TestTreeWildcardConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':names' in new path '/foo/:names' conflicts with existing wildcard ':name' in existing prefix '/foo/:name'

FAIL	github.com/gin-gonic/gin	0.109s
FAIL
