=== RUN   TestP01_PossibleSendOnClosed
--- FAIL: TestP01_PossibleSendOnClosed (0.01s)
panic: send on closed channel [recovered]
	panic: send on closed channel

goroutine 18 [running]:
testing.tRunner.func1.2({0x5510a0, 0x5b1530})
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1737 +0x35e
panic({0x5510a0?, 0x5b1530?})
	/home/ilian/Tools/go-runtime/src/runtime/panic.go:792 +0x132
scenarios.TestP01_PossibleSendOnClosed(0xc0001a0380?)
	/home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go:65 +0x70
testing.tRunner(0xc0001a0380, 0x585da0)
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1851 +0x413
FAIL	scenarios	0.015s
FAIL
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go
TestName:  TestP01_PossibleSendOnClosed
Import added at line: 3
Header added at line: 59
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestP01_PossibleSendOnClosed

Exit Replay with code  30 Send on close
Exit Message: panic: send on closed channel

FAIL	scenarios	0.114s
FAIL
Bugreport info: 0_1,fail
Bugreport info: 0_2,fail
